if [[ ! -v XDG_CONFIG_HOME ]]; then
  echo "Variable XDG_CONFIG_HOME not set!!!"
fi

# Tmux
TERM=screen-256color

# Oh-My-Zsh setup
export ZSH="$XDG_CONFIG_HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Fixes a bug where zsh repeats the command in output
# ref: https://stackoverflow.com/questions/30940299/zsh-repeats-command-in-output
DISABLE_AUTO_TITLE="true"

# Pure prompt
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -U promptinit; promptinit
prompt pure

# Nvm
[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh"

# FZF
if [[ ! "$PATH" == *$(brew --prefix)/opt/fzf/bin* ]]; then
  PATH="${PATH:+${PATH}:}$(brew --prefix)/opt/fzf/bin"
fi
source "$(brew --prefix)/opt/fzf/shell/completion.zsh"
source "$(brew --prefix)/opt/fzf/shell/key-bindings.zsh"

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# Android emulator looks for its config in $HOME, but I want it in $XDG_CONFIG_HOME
alias emulator="HOME=$XDG_CONFIG_HOME emulator"
