if [[ ! -v XDG_CONFIG_HOME ]]; then
  echo "Variable XDG_CONFIG_HOME not set!!!"
fi

# Tmux
TERM=screen-256color

# Oh-My-Zsh setup
export ZSH="$XDG_CONFIG_HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Fixes a bug where zsh repeats the command in output
# ref: https://stackoverflow.com/questions/30940299/zsh-repeats-command-in-output
DISABLE_AUTO_TITLE="true"

# Pure prompt
fpath+=($XDG_CONFIG_HOME/pure)
autoload -U promptinit; promptinit
prompt pure

# Nvm
export NVM_DIR="$XDG_CONFIG_HOME/.nvm"
[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh"

# Pyenv
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
echo 'eval "$(pyenv init -)"' >> ~/.zshrc

# Android emulator looks for its config in $HOME, but I want it in $XDG_CONFIG_HOME
alias emulator="HOME=$XDG_CONFIG_HOME emulator"
